name: maternal_health
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0        # For graphs
  path_provider: ^2.1.3    # For saving image file


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/load.png
  fonts:
    - family: SpotifyCircular
      fonts:
        - asset: assets/fonts/SpotifyCircular.otf

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4FC3A1"
  adaptive_icon_foreground: "assets/logo.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#F0F9F7"
  image: assets/logo.png
  color_dark: "#F0F9F7"
  image_dark: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#F0F9F7"


 