import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';
import 'dart:io';
import '../models/appointment.dart';
import '../config/api_config.dart';
import '../features/auth/services/api_service.dart';

class AppointmentService {
  // Dynamic base URL based on platform - enhanced with centralized config
  static String get baseUrl {
    if (kIsWeb) {
      // For web (Chrome, Firefox, etc.) - use current IP
      return 'http://${ApiConfig.serverIp}:${ApiConfig.serverPort}/api/appointments';
    } else if (Platform.isAndroid) {
      // For Android - use current WiFi IP for real device testing
      return 'http://${ApiConfig.serverIp}:${ApiConfig.serverPort}/api/appointments';
    } else {
      // For iOS simulator and other platforms - use WiFi IP from config
      return ApiConfig.appointmentsUrl;
    }
  }

  // Available time slots
  static const List<String> timeSlots = [
    '08:00 AM',
    '08:30 AM',
    '09:00 AM',
    '09:30 AM',
    '10:00 AM',
    '10:30 AM',
    '11:00 AM',
    '11:30 AM',
    '02:00 PM',
    '02:30 PM',
    '03:00 PM',
    '03:30 PM',
    '04:00 PM',
    '04:30 PM',
  ];

  // Available providers
  static const Map<String, List<Map<String, String>>> providers = {
    'midwife': [
      {
        'id': 'MID001',
        'name': 'Mrs. Kamali Jayasinghe',
        'title': 'Senior Midwife',
      },
    ],
    'doctor': [
      {
        'id': 'DOC001',
        'name': 'Dr. Prasad Wickramasinghe',
        'title': 'General Practitioner',
      },
    ],
  };

  // Get available healthcare providers (dynamic from backend)
  static Future<Map<String, List<Map<String, String>>>>
  getAvailableProviders() async {
    try {
      print('=== Loading available healthcare providers ===');
      final response = await ApiService.getAvailableHealthcareProviders();
      print('API Response: $response');

      Map<String, List<Map<String, String>>> groupedProviders = {
        'midwife': [],
        'doctor': [],
      };

      if (response['success'] == true && response['providers'] is List) {
        final providersList = response['providers'] as List;
        print('Found ${providersList.length} providers from API');

        for (var provider in providersList) {
          print('Processing provider: ${provider}');
          final providerInfo = {
            'id': (provider['medicalLicenseNumber'] ?? '').toString(),
            'name': (provider['fullName'] ?? 'Unknown').toString(),
            'title': (provider['specialization'] ?? 'General').toString(),
            'institution': (provider['institution'] ?? '').toString(),
            'yearsOfExperience':
                (provider['yearsOfExperience']?.toString() ?? '0'),
          };

          print('Provider type: ${provider['providerType']}');
          if (provider['providerType'] == 'MIDWIFE') {
            groupedProviders['midwife']!.add(providerInfo);
            print('Added to midwife group: ${providerInfo}');
          } else if (provider['providerType'] == 'DOCTOR') {
            groupedProviders['doctor']!.add(providerInfo);
            print('Added to doctor group: ${providerInfo}');
          }
        }
      }

      print('Final grouped providers: $groupedProviders');

      // If no providers found, return static ones as fallback
      if (groupedProviders['midwife']!.isEmpty &&
          groupedProviders['doctor']!.isEmpty) {
        return AppointmentService.providers;
      }

      return groupedProviders;
    } catch (e) {
      print('Error loading healthcare providers: $e');
      // Fallback to static providers if API fails
      return AppointmentService.providers;
    }
  }

  // Schedule new appointment
  static Future<Map<String, dynamic>> scheduleAppointment({
    required String motherNic,
    required String motherName,
    required String motherEmail,
    required String appointmentType,
    required String providerName,
    required String providerId,
    required DateTime appointmentDate,
    required String timeSlot,
    String? additionalProblems,
  }) async {
    try {
      final appointment = Appointment(
        id: '', // Will be generated by backend
        motherNic: motherNic,
        motherName: motherName,
        motherEmail: motherEmail,
        appointmentType: appointmentType,
        providerName: providerName,
        providerId: providerId,
        appointmentDate: appointmentDate,
        timeSlot: timeSlot,
        status: 'pending',
        additionalProblems: additionalProblems,
        createdAt: DateTime.now(),
      );

      final response = await http.post(
        Uri.parse('$baseUrl/schedule'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode(appointment.toJson()),
      );

      print('Appointment creation request sent to: $baseUrl/schedule');
      print('Request body: ${jsonEncode(appointment.toJson())}');
      print('Response status: ${response.statusCode}');
      print('Response body: ${response.body}');

      if (response.statusCode == 200 || response.statusCode == 201) {
        final data = jsonDecode(response.body);
        return {
          'success': true,
          'message': 'Appointment scheduled successfully',
          'appointment': Appointment.fromJson(
            data,
          ), // data is the appointment directly
        };
      } else {
        final error = jsonDecode(response.body);
        print(
          'Appointment creation failed: ${response.statusCode}, Body: ${response.body}',
        );
        return {
          'success': false,
          'message':
              error['error'] ??
              error['message'] ??
              'Failed to schedule appointment', // Handle both error formats
        };
      }
    } catch (e) {
      return {'success': false, 'message': 'Network error: ${e.toString()}'};
    }
  }

  // Get appointments by mother NIC
  static Future<Map<String, dynamic>> getAppointmentsByNic(
    String motherNic,
  ) async {
    try {
      print('Fetching appointments for NIC: $motherNic');
      final response = await http.get(
        Uri.parse('$baseUrl/mother/$motherNic'),
        headers: {'Content-Type': 'application/json'},
      );

      print('Response status: ${response.statusCode}');
      print('Response body: ${response.body}');

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final appointments =
            (data as List) // data is the list directly
                .map((json) => Appointment.fromJson(json))
                .toList();

        print('Successfully parsed ${appointments.length} appointments');
        return {'success': true, 'appointments': appointments};
      } else {
        print('API error: ${response.statusCode}');
        // Return empty list instead of error for better UX
        return {'success': true, 'appointments': <Appointment>[]};
      }
    } catch (e) {
      print('Network error fetching appointments: ${e.toString()}');
      return {
        'success': true, // Return success with empty list for better UX
        'appointments': <Appointment>[],
      };
    }
  }

  // Get today's appointments for providers
  static Future<Map<String, dynamic>> getTodayAppointments(
    String providerId,
  ) async {
    try {
      final today = DateTime.now();
      final dateStr =
          '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';

      final response = await http.get(
        Uri.parse('$baseUrl/provider/$providerId/date/$dateStr'),
        headers: {'Content-Type': 'application/json'},
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final appointments = (data['appointments'] as List)
            .map((json) => Appointment.fromJson(json))
            .toList();

        return {'success': true, 'appointments': appointments};
      } else {
        return {
          'success': false,
          'message': 'Failed to fetch appointments',
          'appointments': <Appointment>[],
        };
      }
    } catch (e) {
      return {
        'success': false,
        'message': 'Network error: ${e.toString()}',
        'appointments': <Appointment>[],
      };
    }
  }

  // Search appointments by NIC (for providers)
  static Future<Map<String, dynamic>> searchAppointmentsByNic(
    String nic,
  ) async {
    try {
      final response = await http.get(
        Uri.parse('$baseUrl/search?nic=$nic'),
        headers: {'Content-Type': 'application/json'},
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final appointments = (data['appointments'] as List)
            .map((json) => Appointment.fromJson(json))
            .toList();

        return {'success': true, 'appointments': appointments};
      } else {
        return {
          'success': false,
          'message': 'No appointments found',
          'appointments': <Appointment>[],
        };
      }
    } catch (e) {
      return {
        'success': false,
        'message': 'Network error: ${e.toString()}',
        'appointments': <Appointment>[],
      };
    }
  }

  // Mark appointment as completed
  static Future<Map<String, dynamic>> markAsCompleted(
    String appointmentId,
    String? notes,
  ) async {
    try {
      final response = await http.put(
        Uri.parse('$baseUrl/$appointmentId/complete'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'notes': notes,
          'updatedAt': DateTime.now().toIso8601String(),
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return {
          'success': true,
          'message': 'Appointment marked as completed',
          'appointment': Appointment.fromJson(data['appointment']),
        };
      } else {
        final error = jsonDecode(response.body);
        return {
          'success': false,
          'message': error['message'] ?? 'Failed to update appointment',
        };
      }
    } catch (e) {
      return {'success': false, 'message': 'Network error: ${e.toString()}'};
    }
  }

  // Cancel appointment
  static Future<Map<String, dynamic>> cancelAppointment(
    String appointmentId,
  ) async {
    try {
      final response = await http.put(
        Uri.parse('$baseUrl/$appointmentId/cancel'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({'updatedAt': DateTime.now().toIso8601String()}),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return {
          'success': true,
          'message': 'Appointment cancelled successfully',
          'appointment': Appointment.fromJson(data['appointment']),
        };
      } else {
        final error = jsonDecode(response.body);
        return {
          'success': false,
          'message': error['message'] ?? 'Failed to cancel appointment',
        };
      }
    } catch (e) {
      return {'success': false, 'message': 'Network error: ${e.toString()}'};
    }
  }

  // Get available time slots
  static Future<Map<String, dynamic>> getAvailableTimeSlots(
    DateTime date,
    String providerId,
  ) async {
    try {
      final dateStr =
          '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

      final response = await http.get(
        Uri.parse(
          '$baseUrl/available-slots?date=$dateStr&providerId=$providerId',
        ),
        headers: {'Content-Type': 'application/json'},
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return {
          'success': true,
          'availableSlots': List<String>.from(data['availableSlots']),
        };
      } else {
        // If backend endpoint fails, return all time slots as available
        print('Available slots API failed with status: ${response.statusCode}');
        return {
          'success': true, // Changed to true so UI doesn't show error
          'availableSlots': timeSlots,
        };
      }
    } catch (e) {
      // If network error, return all time slots as available
      print('Available slots network error: ${e.toString()}');
      return {
        'success': true, // Changed to true so UI doesn't show error
        'availableSlots': timeSlots,
      };
    }
  }

  // Delete old appointments (cleanup service)
  static Future<Map<String, dynamic>> deleteOldAppointments() async {
    try {
      final response = await http.delete(
        Uri.parse('$baseUrl/cleanup'),
        headers: {'Content-Type': 'application/json'},
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return {
          'success': true,
          'message': data['message'] ?? 'Old appointments cleaned up',
          'deletedCount': data['deletedCount'] ?? 0,
        };
      } else {
        return {
          'success': false,
          'message': 'Failed to cleanup old appointments',
        };
      }
    } catch (e) {
      return {'success': false, 'message': 'Network error: ${e.toString()}'};
    }
  }
}
